/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ies.ed.solitario;

import ies.ed.solitario.utils.ZonaIntercambio;
import java.util.ArrayList;
import javafx.application.Application;
import javafx.application.Platform;
import javafx.event.ActionEvent;
import javafx.event.Event;
import javafx.event.EventHandler;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.control.MenuItem;
import javafx.scene.image.ImageView;
import javafx.scene.input.ClipboardContent;
import javafx.scene.input.DragEvent;
import javafx.scene.input.Dragboard;
import javafx.scene.input.MouseEvent;
import javafx.scene.input.TransferMode;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.Pane;
import javafx.scene.layout.StackPane;
import javafx.scene.layout.VBox;
import javafx.scene.text.Text;
import javafx.stage.Stage;

public class App extends Application {

    @FXML
    MenuItem opcionsalir;
    @FXML
    MontonBaraja montonbaraja;
    @FXML
    MontonJuego m1;
    @FXML
    MontonJuego m2;
    @FXML
    MontonJuego m3;
    @FXML
    MontonJuego m4;
    @FXML
    MontonJuego m5;
    @FXML
    MontonJuego m6;
    @FXML
    MontonJuego m7;
    @FXML
    MontonPalo p1;
    @FXML
    MontonPalo p2;
    @FXML
    MontonPalo p3;
    @FXML
    MontonPalo p4;
    
    // @FXML
    // CartaComponent carta1;
    // @FXML
    // CartaComponent carta2;
    @FXML
    BarajaComponent baraja;
   
    private void initBaraja() {

        baraja.createCartas(true);
        baraja.setOnMouseClicked(new EventHandler<Event>() {

            @Override
            public void handle(Event event) {
                // TODO Auto-generated method stub
                CartaComponent c = baraja.destaparCarta();
                if (c != null) {
                    montonbaraja.amontonar(c);
                } else {
                    baraja.rellenar(montonbaraja.vaciar());
                }
            }

        });
        this.repartir(baraja, m1, 1);
        this.repartir(baraja, m2, 2);
        this.repartir(baraja, m3, 3);
        this.repartir(baraja, m4, 4);
        this.repartir(baraja, m5, 5);
        this.repartir(baraja, m6, 6);
        this.repartir(baraja, m7, 7);
    }

    private void repartir(BarajaComponent b, MontonComponent m, int cartas) {
        CartaComponent c;
        for (int i = 0; i < cartas; i++) {
            c = b.getCartaCima();
            m.amontonar(c);
            if (i == cartas - 1) {
                c.destapar();
            } else {
                c.tapar();
            }
        }
    }

    @Override
    public void start(Stage primaryStage) {
        try {
            FXMLLoader loader = new FXMLLoader(getClass().getResource("/main.fxml"));
            loader.setController(this);
            // Parent root =
            // FXMLLoader.load(getClass().getResource("view/Calculatorview.fxml"));
            VBox root = (VBox) loader.load();

            Scene scene = new Scene(root);

            primaryStage.setScene(scene);
            primaryStage.show();

            /*
             * carta1.setOnMousePressed(new EventHandler<MouseEvent>() {
             * 
             * @Override
             * public void handle(MouseEvent t) {
             * selected = carta1;
             * }
             * 
             * });
             * carta2.setOnMousePressed(new EventHandler<MouseEvent>() {
             * 
             * @Override
             * public void handle(MouseEvent t) {
             * selected = carta2;
             * }
             * 
             * });
             */

        } catch (Exception e) {
            e.printStackTrace();
        }
        this.initBaraja();
    }

    @FXML
    protected void handleSubmitButtonAction(ActionEvent event) {
        Platform.exit();
        System.exit(0);

    }

    public static void main(String[] args) {
        launch(args);
    }
}
